
1. Create a one-dimension array with random integers between 0 and 20. The size of the array is 10. Ensure that the results are reproducible.

In [1]:

import numpy as np

rng = np.random.default_rng(seed=42)
array1 = rng.integers(21, size=10)
array1


array([ 1, 16, 13,  9,  9, 18,  1, 14,  4,  1])

2. Using slicing, create a subset array of 3 integers from the array you created in question 1. First integer is at index 2, second integer is at index 4 and third index at index 7.

In [2]:
subset_array = array1[[2, 4, 7]]
print(subset_array)

[13  9 14]



3. Create a two-dimension array from the list below. Check the dimensions and shape of your array
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11, 12, 13, 14, 15]]
Using slicing, write a code to access the numbers 3, 8, 13. Your code should return [3, 8, 13].

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

# Convert the list to a NumPy array
array2 = np.array(my_list)
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
array2.ndim

2

In [5]:
array2.shape

(3, 5)

In [6]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

# Convert the list to a NumPy array
array2 = np.array(my_list)

# Use slicing to access the desired elements
sub_array = array2[0, 2], array2[1, 2], array2[2,2]
print(np.array(sub_array))

[ 3  8 13]



4. Create a three-dimension array from the nested list below:
my_list = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]
Using slicing, write a code that creates a sub list from the array you created. Your code should return an array of 4, 8 and 15.

In [7]:

my_list = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]

# Convert the nested list to a NumPy array
array3 = np.array(my_list)

# Use slicing to create the sub list
sub_list = array3[0,0,3], array3[0,1,2], array3[0,2,4]
np.array(sub_list)

array([ 4,  8, 15])